// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Image4;
void ui_event_Switch2( lv_event_t * e);
lv_obj_t *ui_Switch2;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label5;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch2( lv_event_t * e) {
  lv_event_code_t event_code = lv_event_get_code(e); lv_obj_t * target = lv_event_get_target(e);
  if ( event_code == LV_EVENT_CLICKED) {
    _ui_checked_set_text_value( ui_Label1, target, "ON", "OFF");
    led_flag_Lock = 1;
    led_flag = !led_flag;
  }
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Image2 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image2, &ui_img_small_temp_png);
  lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 75
  lv_obj_set_x( ui_Image2, 3 );
  lv_obj_set_y( ui_Image2, 24 );
  lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
  lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Image1 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image1, &ui_img_small_hum_png);
  lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 75
  lv_obj_set_x( ui_Image1, 141 );
  lv_obj_set_y( ui_Image1, 34 );
  lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
  lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Image3 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image3, &ui_img_small_logo_png);
  lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 250
  lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 52
  lv_obj_set_x( ui_Image3, -4 );
  lv_obj_set_y( ui_Image3, -96 );
  lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
  lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Image4 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image4, &ui_img_small_off_png);
  lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 50
  lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 75
  lv_obj_set_x( ui_Image4, -159 );
  lv_obj_set_y( ui_Image4, 14 );
  lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
  lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
  lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Switch2 = lv_switch_create(ui_Screen1);
  lv_obj_set_width( ui_Switch2, 50);
  lv_obj_set_height( ui_Switch2, 25);
  lv_obj_set_x( ui_Switch2, -158 );
  lv_obj_set_y( ui_Switch2, 68 );
  lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );

  ui_Panel2 = lv_obj_create(ui_Screen1);
  lv_obj_set_width( ui_Panel2, 90);
  lv_obj_set_height( ui_Panel2, 30);
  lv_obj_set_x( ui_Panel2, -155 );
  lv_obj_set_y( ui_Panel2, 114 );
  lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
  lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Label2 = lv_label_create(ui_Panel2);
  lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label2, -18 );
  lv_obj_set_y( ui_Label2, 0 );
  lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label2, "State:  ");
  lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFD0834), LV_PART_MAIN | LV_STATE_DEFAULT );
  lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label1 = lv_label_create(ui_Panel2);
  lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label1, 20 );
  lv_obj_set_y( ui_Label1, 1 );
  lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label1, "OFF");

  ui_Panel1 = lv_obj_create(ui_Screen1);
  lv_obj_set_width( ui_Panel1, 60);
  lv_obj_set_height( ui_Panel1, 30);
  lv_obj_set_x( ui_Panel1, -1 );
  lv_obj_set_y( ui_Panel1, 117 );
  lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
  lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Label4 = lv_label_create(ui_Panel1);
  lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label4, -11 );
  lv_obj_set_y( ui_Label4, 2 );
  lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label4, "29");

  ui_Label3 = lv_label_create(ui_Panel1);
  lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label3, 13 );
  lv_obj_set_y( ui_Label3, 2 );
  lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label3, "°C");
  lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFB0606), LV_PART_MAIN | LV_STATE_DEFAULT );
  lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel4 = lv_obj_create(ui_Screen1);
  lv_obj_set_width( ui_Panel4, 60);
  lv_obj_set_height( ui_Panel4, 30);
  lv_obj_set_x( ui_Panel4, 143 );
  lv_obj_set_y( ui_Panel4, 121 );
  lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
  lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

  ui_Label6 = lv_label_create(ui_Panel4);
  lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label6, -9 );
  lv_obj_set_y( ui_Label6, 1 );
  lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label6, "55");

  ui_Label5 = lv_label_create(ui_Panel4);
  lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_x( ui_Label5, 15 );
  lv_obj_set_y( ui_Label5, 1 );
  lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
  lv_label_set_text(ui_Label5, "%");
  lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF90606), LV_PART_MAIN | LV_STATE_DEFAULT );
  lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Screen1_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr( ui_Screen1);
}
