// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
void ui_event_Switch2( lv_event_t * e);
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui____initial_actions0;
extern int led_flag_Lock;
extern int led_flag;


LV_IMG_DECLARE( ui_img_small_temp_png);   // assets\small_temp.png
LV_IMG_DECLARE( ui_img_small_hum_png);   // assets\small_hum.png
LV_IMG_DECLARE( ui_img_small_logo_png);   // assets\small_logo.png
LV_IMG_DECLARE( ui_img_small_off_png);   // assets\small_off.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
